[project]
name = "iqe-wheels"
description = "Binary wheels for IQE dependencies that require compilation"
readme = "README.md"
requires-python = ">=3.12"
authors = [
  {name = "Nikhil Dhandre", email = "ndhandre@redhat.com"},
]
maintainers = [
  {name = "Nikhil Dhandre", email = "ndhandre@redhat.com"},
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Testing",
  "Operating System :: OS Independent",
  "Private :: Do Not Upload",
]
dynamic = ["version"]
keywords = ["iqe", "wheels", "binary", "pip"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "hatch-vcs"]

[tool.hatch.version]
raw-options.version_scheme = "calver-by-date"
source = "vcs"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["F", "I", "UP"]
